# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.send_email:
        class: AppBundle\Service\SendEmail
        arguments: ["@mailer", "@templating"]

  #  services:
  #      my_user_provider:
  #          class: AppBundle\Service\FOSUBUserProvider
            #this is the place where the properties are passed to the UserProvider - see config.yml
  #          arguments: ["@fos_user.user_manager", {facebook: facebook_id}]


  #  app.facebook_authenticator:
  #      class: AppBundle\Service\FacebookAuthenticator
  #      arguments: ["@oauth2.registry", "@doctrine.orm.entity_manager", "@router"]