# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.send_email:
        class: AppBundle\Service\RegisterEmail
        arguments: ["@mailer", "@templating"]

    app.facebook_authenticator:
        class: AppBundle\Service\FacebookAuthenticator
        arguments: ["@oauth2.registry", "@doctrine.orm.entity_manager", "@router"]

    app.question_switcher:
        class: AppBundle\Service\QuestionSwitcher
        arguments: ["@session", "@security.token_storage", "@doctrine.orm.entity_manager"]

    app.question_checker:
        class: AppBundle\Service\QuestionChecker
        arguments: ["@session", "@doctrine.orm.entity_manager"]

    app.test_question:
        class: AppBundle\Form\TestQuestionType
        arguments: ["@app.question_checker"]
        tags:
            - { name: form.type }